-- ============================================================
-- GOVERNANCE: RBAC, Dynamic Masking, Object Tags
-- ============================================================
-- Principle: Least privilege access with classification
--   - DOL_ANALYST: Full Gold access (internal team)
--   - UTILITY_READER: Only shared views, masked zip codes
--   - DATA_ENGINEER: Full pipeline access (Bronze + Silver + Gold)
-- ============================================================

USE DATABASE EV_PIPELINE;

-- ==================
-- ROLES
-- ==================
CREATE ROLE IF NOT EXISTS DOL_ANALYST;
CREATE ROLE IF NOT EXISTS UTILITY_READER;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;

-- DOL_ANALYST: Full read on Gold layer
GRANT USAGE ON DATABASE EV_PIPELINE TO ROLE DOL_ANALYST;
GRANT USAGE ON SCHEMA EV_PIPELINE.GOLD TO ROLE DOL_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA EV_PIPELINE.GOLD TO ROLE DOL_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA EV_PIPELINE.GOLD TO ROLE DOL_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA EV_PIPELINE.GOLD TO ROLE DOL_ANALYST;

-- UTILITY_READER: Only shared views (restricted)
GRANT USAGE ON DATABASE EV_PIPELINE TO ROLE UTILITY_READER;
GRANT USAGE ON SCHEMA EV_PIPELINE.GOLD TO ROLE UTILITY_READER;
GRANT SELECT ON VIEW EV_PIPELINE.GOLD.SHARED_UTILITY_DEMAND TO ROLE UTILITY_READER;
GRANT SELECT ON VIEW EV_PIPELINE.GOLD.SHARED_EV_COUNTY_TRENDS TO ROLE UTILITY_READER;

-- DATA_ENGINEER: All schemas (pipeline maintenance)
GRANT USAGE ON DATABASE EV_PIPELINE TO ROLE DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EV_PIPELINE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA EV_PIPELINE.BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA EV_PIPELINE.SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA EV_PIPELINE.GOLD TO ROLE DATA_ENGINEER;

-- ==================
-- DYNAMIC MASKING
-- ==================
-- Mask zip codes: UTILITY_READER sees only first 3 digits (regional, not exact)
USE SCHEMA GOLD;

CREATE OR REPLACE MASKING POLICY GOLD.ZIP_MASK AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'DOL_ANALYST', 'DATA_ENGINEER') THEN val
        ELSE LEFT(val, 3) || '**'
    END;

-- Apply to Silver layer
ALTER DYNAMIC TABLE SILVER.EV_REGISTRATIONS 
    MODIFY COLUMN zip_code SET MASKING POLICY GOLD.ZIP_MASK;

-- ==================
-- OBJECT TAGS
-- ==================
-- Classification for compliance and data catalog
CREATE TAG IF NOT EXISTS GOLD.PII COMMENT = 'Personally Identifiable Information';
CREATE TAG IF NOT EXISTS GOLD.GEOGRAPHIC COMMENT = 'Geographic/Location data';
CREATE TAG IF NOT EXISTS GOLD.FINANCIAL COMMENT = 'Financial/Pricing data';

-- Apply tags
ALTER DYNAMIC TABLE SILVER.EV_REGISTRATIONS MODIFY COLUMN zip_code SET TAG GOLD.PII = 'zip_code';
ALTER DYNAMIC TABLE SILVER.EV_REGISTRATIONS MODIFY COLUMN county SET TAG GOLD.GEOGRAPHIC = 'county';
ALTER DYNAMIC TABLE SILVER.EV_REGISTRATIONS MODIFY COLUMN base_msrp SET TAG GOLD.FINANCIAL = 'msrp';

-- ==================
-- VERIFY
-- ==================
SHOW ROLES;
SHOW MASKING POLICIES IN SCHEMA GOLD;
SHOW TAGS IN SCHEMA GOLD;

-- Test masking (switch role to see effect)
-- USE ROLE UTILITY_READER;
-- SELECT zip_code FROM SILVER.EV_REGISTRATIONS LIMIT 5;
-- Expected: "980**", "981**", etc.
